spring.application.name=DesafioItau
# URL de conexão (troque 'nome_do_seu_banco' pelo banco que você criou no Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/desafioitau
spring.datasource.username=postgres
spring.datasource.password=

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
